#!/bin/zsh

_handle_tmux() {
    case $1 in
        (work)
            ~/.dotfiles/tmux.work
        ;;
        (monitor)
            ~/.dotfiles/tmux.monitor
        ;;
   esac
}

_handle_radio() {
    mplayer $(cat ~/.dotfiles/radio.m3u | fzf)
}

_handle_mount() {
    case $1 in
        (user)
            if grep -qs '/mnt/iv/user' /proc/mounts; then
            else
                sudo mount -t cifs //srv-iv2-n/user /mnt/iv/user -o username=saj,gid=1001,uid=1001,iocharset=utf8,sec=ntlmv2,vers=1.0
            fi
        ;;
        (home)
            if grep -qs '/mnt/iv/home' /proc/mounts; then
            else
                sudo mount -t cifs //srv-iv2-n/Home/saj /mnt/iv/home -o username=saj,gid=1001,uid=1001,iocharset=utf8,sec=ntlmv2,vers=1.0
            fi
        ;;
   esac
}

_handle_jenkins() {
    case $1 in
        (build)
            local target
            target="$(java -jar ~/.local/bin/jenkins-cli.jar -s http://iv-build-01:8080/ list-jobs 2>/dev/null | fzf)"
            echo $target
            [ -z $target ] || java -jar ~/.local/bin/jenkins-cli.jar -s http://iv-build-01:8080/ build $target -f
        ;;
        (console)
            local target
            target="$(java -jar ~/.local/bin/jenkins-cli.jar -s http://iv-build-01:8080/ list-jobs 2>/dev/null | fzf)"
            echo $target
            [ -z $target ] || java -jar ~/.local/bin/jenkins-cli.jar -s http://iv-build-01:8080/ console $target
        ;;
   esac
}

_handle_rdp() {
    case $1 in
        (db)
            xfreerdp +clipboard /u:Administrator /v:db.iv.lan /f /drive:shared,/home/saj/share
        ;;
        (visio)
            xfreerdp +clipboard /u:intervista\\saj /v:iv-tsplus-01 /f /drive:shared,/home/saj/share
        ;;
        (iv-ts)
            xfreerdp +clipboard /u:intervista\\saj /v:iv-ts /f /drive:shared,/home/saj/share
        ;;
   esac
}

case $1 in
    (tmux)
        shift
        _handle_tmux $1
    ;;
    (radio)
        _handle_radio
    ;;
    (mount)
        shift
        _handle_mount $1
    ;;
    (umount)
        sudo umount -a -t cifs -l
    ;;
    (jenkins)
        shift
        _handle_jenkins $1
    ;;
    (rdp)
        shift
        _handle_rdp $1
    ;;
esac

return 0
