set-option -g default-terminal "screen-256color"
set-option -g status-utf8 on
set-option -g history-limit 20000
set-option -g pane-active-border-fg blue
set-option -g buffer-limit 3

set-window-option -g monitor-activity on

set-window-option -g mode-keys vi
set-window-option -g mode-mouse on

bind-key -n C-Left next-window
bind-key -n C-Right previous-window

source-file ~/.dotfiles/gist/tarruda/5158535/.tmux.conf
