#!/bin/bash

DONE="........................................................... done"
ERROR="........................................................... error"

MESSAGE="pulling fzf"
printf "$MESSAGE" && cd fzf && git checkout master >/dev/null 2>&1 && git pull >/dev/null 2>&1 && ./install --all >/dev/null 2>&1 && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}
cd ..

MESSAGE="pulling elinks"
printf "$MESSAGE" && cd elinks && git checkout master >/dev/null 2>&1 && git pull >/dev/null 2>&1 && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}
cd ..

MESSAGE="pulling oh-my-zsh"
printf "$MESSAGE" && cd oh-my-zsh && git checkout master >/dev/null 2>&1 && git pull >/dev/null 2>&1 && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}
cd ..

MESSAGE="pulling todo.txt-cli"
printf "$MESSAGE" && cd todo.txt-cli && git checkout master >/dev/null 2>&1 && git pull >/dev/null 2>&1 && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}
cd ..

MESSAGE="pulling base16-gnome-terminal"
printf "$MESSAGE" && cd base16-gnome-terminal && git checkout master >/dev/null 2>&1 && git pull >/dev/null 2>&1 && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}
cd ..

MESSAGE="pulling gist/tarruda/5158535"
printf "$MESSAGE" && cd gist/tarruda/5158535 && git checkout master >/dev/null 2>&1 && git pull >/dev/null 2>&1 && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}
cd ../../..

MESSAGE="pulling vim/autoload"
printf "$MESSAGE" && cd vim/autoload && git checkout master >/dev/null 2>&1 && git pull >/dev/null 2>&1 && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}
cd ..
