#!/bin/bash

DONE="........................................................... done"
ERROR="........................................................... error"

MESSAGE="Create ~/.bin directory"
printf "$MESSAGE"
mkdir -p ~/.bin &> /dev/null && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}

MESSAGE="Installing submodules"
printf "$MESSAGE"
git submodule update --init --recursive &> /dev/null && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}

declare -A FILES

FILES[~/.zshrc]=~/.dotfiles/zshrc
FILES[~/.tmux.conf]=~/.dotfiles/tmux.conf
FILES[~/.elinks]=~/.dotfiles/elinks
FILES[~/.fzf]=~/.dotfiles/fzf
FILES[~/.oh-my-zsh]=~/.dotfiles/oh-my-zsh
FILES[~/.vim]=~/.dotfiles/vim
FILES[~/.vimrc]=~/.dotfiles/vimrc
FILES[~/.dotfiles/oh-my-zsh/custom/themes]=~/.dotfiles/themes
FILES[~/.bin/vim-tmux-move.zsh]=~/.dotfiles/gist/tarruda/5158535/vim-tmux-move.zsh
FILES[~/.bin/vim-tmux-xpaste.zsh]=~/.dotfiles/gist/tarruda/5158535/vim-tmux-xpaste.zsh
FILES[~/.bin/vim-tmux-open.zsh]=~/.dotfiles/gist/tarruda/5158535/vim-tmux-open.zsh

EXISTS="........................................................... exists"
CREATING="........................................................... creating"

for i in "${!FILES[@]}"
do
  if [ -e $i ]; then
    echo $i" "${EXISTS:${#i}}
  else
    echo $i" "${CREATING:${#i}}
    ln -s ${FILES[$i]} $i
  fi
done

MESSAGE="Installing FZG"
printf "$MESSAGE"
~/.fzf/install --all &> /dev/null && echo " "${DONE:${#MESSAGE}} || echo " "${ERROR:${#MESSAGE}}
