set draw_borders both
set preview_images true
set use_preview_script true

map X chain shell vim -p ~/.config/ranger/rc.conf %rangerdir/config/rc.conf; source ~/.config/ranger/rc.conf
# map f console scout -ftsea%space
